#!/usr/bin/env python3
"""Neuter the RFS symlink rules in the generated proprietary blobs directory.

fp4-proprietary/coretech-config-vendor/tftp/Android.mk builds /vendor/rfs with
$(call symlink-file,...). Those symlinks land in the staging directory but are
owned by no module, so they never reach vendor.img - on device /vendor/rfs held
only the 0-byte rfs_symlinks marker. tftp_server then failed every modem RFS
request with ENOENT, the modem could not read its MCFG (modem_pr/so/649_0_0.mbn)
or wlanmdsp.mbn, and it sat in DMS operating mode 3 (OFFLINE) answering
DMS_SET_OPERATING_MODE(ONLINE) with QMI_ERR_DEVICE_NOT_READY. No radio, no wlan0.

The tree now builds that same tree from tracked install_symlink modules in
device/fairphone/FP4/rfs/Android.bp. Both definitions cannot coexist - they emit
the same targets and kati dies with "overriding commands for target
.../vendor/rfs/msm/mpss/ramdumps" - so this empties the macro that generates
them.

device/fairphone/fp4-proprietary is generated by
vendor/fairphone/tools/bin/get_blobs.py and is not a git repo, so re-extracting
blobs restores the broken version. Run this afterwards, like patch_needed.py.

Idempotent; safe to run repeatedly.
"""

import sys
from pathlib import Path

TFTP_MK = Path("device/fairphone/fp4-proprietary/coretech-config-vendor/tftp/Android.mk")

ORIGINAL = """define symlink-rfs
$(call symlink-file,,$(1),$(2)) \\
$(eval RFS_SYMLINKS_DEPS += $(2))
endef"""

REPLACEMENT = """# NEUTERED by device/fairphone/FP4/tools/disable_rfs_symlinks.py.
# The symlinks are built by tracked install_symlink modules in
# device/fairphone/FP4/rfs/Android.bp instead; see that file and the script for
# why. Keeping both emits duplicate targets and kati fails.
define symlink-rfs
endef"""

# An empty macro body is the thing that matters, whatever comment sits above it,
# so hand-edits are recognised too.
NEUTERED = "define symlink-rfs\nendef"


def main() -> int:
    if not TFTP_MK.exists():
        print(f"{TFTP_MK}: not found - run from the top of the tree, after get_blobs.py")
        return 1

    text = TFTP_MK.read_text()

    if NEUTERED in text:
        print(f"{TFTP_MK}: already neutered, nothing to do")
        return 0

    if ORIGINAL not in text:
        print(
            f"{TFTP_MK}: symlink-rfs macro does not look the way we expect.\n"
            "The blobs may have changed - check by hand whether it still creates\n"
            "/vendor/rfs symlinks that would collide with device/fairphone/FP4/rfs."
        )
        return 1

    TFTP_MK.write_text(text.replace(ORIGINAL, REPLACEMENT))
    print(f"{TFTP_MK}: symlink-rfs neutered")
    return 0


if __name__ == "__main__":
    sys.exit(main())
